# version: '3.8'

services:
  backend:
    build: ./ucon_backend
    container_name: django_app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./ucon_backend:/app
      - static_volume:/app/staticfiles
    env_file:
      - ./ucon_backend/.env
    depends_on:
      - db

  nginx:
    build: ./ucon_frontend
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: uconadmin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  static_volume:
  postgres_data:
