# version: '3.8'

services:
  backend:
    build: ./ucon_backend
    container_name: django_app
    expose:
      - "8000"
    ports:
      - "8000:8000"  # Optional, for host access if needed
    volumes:
      - ./ucon_backend:/app
      - static_volume:/app/staticfiles  # shared volume for static files

    env_file:
      - ./ucon_backend/.env
    depends_on:
      - db

  frontend:
    build: ./ucon_frontend
    container_name: react_app
    depends_on:
      - backend
    volumes:
      - ./ucon_frontend:/app
      
    # React will be served via nginx

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ucon_frontend/nginx.conf:/etc/nginx/conf.d/app.conf:ro # Mounts your config into the standard Nginx location inside the container. ':ro' makes it read-only.
      - ./ucon_frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles  # match this path with STATIC_ROOT

    depends_on:
      - frontend
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: uconadmin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  static_volume:
  postgres_data:
