# Generated by Django 5.2 on 2025-04-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='user_role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_pk',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
